### ISSUE TITLE
Check for releases

### ISSUE THREAD

**Issue by benbalter** [jollygoodcode/whatsnew#7]
Many projects uses the native [Releases](https://github.com/blog/1547-release-your-software) functionality to document changes between versions. (see e.g., [licensee as an example](https://github.com/benbalter/licensee/releases)).

It'd be awesome if the Gem could use Octokit to check the release history to see if releases have descriptions, in the event that on changelog file is found.

**Comment by JuanitoFatas** [comment]
Thanks for the suggestions :+1: 

I imagine a output incorporate with GitHub releases will look like this:

```
$ whatsnew

What's New?

Release Note:

* Properly check for `YAML#safe_load` support
* Properly return `nil` from `Project#license_hash` when no license is found

https://github.com/benbalter/licensee/releases/tag/v4.7.2

See CHANGELOG.md: https://github.com/jollygoodcode/whatsnew/blob/master/CHANGELOG.md for full details.
```

Let's define three things for me to refer later:

1. `release note content`

  ```
  Release Note:

  * Properly check for `YAML#safe_load` support
  * Properly return `nil` from `Project#license_hash` when no license is found
  ```

2. `release url`

  ```
  https://github.com/benbalter/licensee/releases/tag/v4.7.2
  ```

3. `news content`

  ```
  See CHANGELOG.md: https://github.com/jollygoodcode/whatsnew/blob/master/CHANGELOG.md for full details.
  ```

Few scenarios:

1. Gem did not have changelog and did not have GitHub releases ([vmg/sundown](https://github.com/vmg/sundown))

  Not found.

2. Gem did not have changelog and have GitHub releases ([octokit/octokit.rb](https://github.com/octokit/octokit.rb))

  `whatsnew` should return latest ` release note content` info from command line output. This could be wrong, because some author release a version but did not create GitHub releases.

3. Gem kept a changelog and did not have GitHub releases feature at all ([seattlerb/minitest](https://github.com/seattlerb/minitest))

  `whatsnew` should return `news content`.

4. Gem kept a changelog and have GitHub releases ([rspec/rspec-rails](https://github.com/rspec/rspec-rails))

  `whatsnew` should return `news content`, return its GitHub `releases url`, but do not output latest `release note content` because we can't be sure if latest_release is the *latest* matches changelog content.

5. Gem under a metagem (activesupport under rails/rails)

  Not found or special rule for this kind of gem.

Does these matched your feature in mind? Anything missing? Thanks! :bow:

**Comment by JuanitoFatas** [comment]
@benbalter 1.0.0 released with support of searching releases if changelog cannot be found. Please see README for more details. :smile:
